### ISSUE TITLE
Fold in The GMP Site Work into the Audio Reviewer App

### ISSUE THREAD

**Issue by Mekebrown** [Mekebrown/githubbubber.github.io#20]
Months ago I restarted an unpublished audio reviewer NEXT js app for the existing clients of the studio. The current work is locally saved. Any client in need of reviewing audio recently recorded would be able to right away since editing changes would automatically be published to an AWS S3 bucket. The client can then log in and listen to it w/o contacting GSN engineers, making notes on the audio as soon as they have comments or questions for it.

The Next JS app ([repo is found here](https://github.com/Githubbubber/gsn-audio-review-app)) is currently very lightweight, has common models and schemas, and the design is based on a very paired-down version of [an Envato template](https://elements.envato.com/montu-admin-for-social-music-sharing-platform-88564R). 

This repo's GMP site work can easily **replace the audio reviewer app's static pages**. We can continue right where we left off in our work here!

All that's needed to be done is for me to do the following:
- push my local revamp of the reviewer to[ its repo](https://github.com/Githubbubber/gsn-audio-review-app)
- add the current reviewer app's code to [that repo](https://github.com/Githubbubber/gsn-audio-review-app)
- continue with building out the html/css/js here (for me it's the home, services, and portfolio pages along with secondary pages like the privacy policy)
- start the pairing fun of converting the html/css/js work to React with you!

Easy peasy, at our own pace, and we will pair as much as our schedules will allow.

**Comment by Githubbubber** [comment]
The long term goal is to:
- finish every static page  
- close out this repo

If either of us choose to complete a page in the reviewer app repo we can close out its issue(s), board item(s), and/or pull request(s) in this repo and create an issue(s), board item(s), and/or pull request(s) in _that_ repo.
